name: Unittest Check

on: [push, pull_request]

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
      shell: bash
    

    - name: Run Unittest
      run: |
        python3 -m unittest discover test/
      shell: bash