name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: Flake8 Check
      uses: ./.github/actions/flake8
